[custom]



;设置规则标志位
; -下载协议和局域网白名单
ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
; -谷歌国内可直连部分（优先直连）
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/GoogleCN.list
ruleset=DIRECT,https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/GoogleCNProxyIP.list
; -谷歌全家桶服务（专属骨干网）
ruleset=📢 Google 服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 Google 服务,https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Google.list
ruleset=📢 Google 服务,https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/GoogleEarth.list
ruleset=📢 Google 服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
; -微软与苹果
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
; -国内规则补充
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
; -国内域名与 IP（零 DNS 泄露直连）
ruleset=DIRECT,[]GEOSITE,geolocation-cn
ruleset=DIRECT,[]GEOIP,cn,no-resolve
; -终极兜底（其他所有网站）
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位



;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]📢 Google 服务`[]DIRECT`[]REJECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📢 Google 服务`select`[]♻️ 自动选择`[]DIRECT`[]REJECT`.*
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🚀 节点选择`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*
;设置分组标志位



enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
